# Generated by Django 4.1.3 on 2022-12-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=60)),
                ("state_province", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=50)),
                ("website", models.URLField()),
            ],
            options={"ordering": ["-name"],},
        ),
    ]
